refactor data transformation
aleks-luk/de_projects pull request #3
Opened 2024-06-30 16:35 UTC by aleks-luk

2024-07-23 20:39 UTC, aleks-luk commented
Grzegorz, my thoughts:

-  I think we should we should delete function save to csv from scrapper_books.py in order to have transformation and saving files in one place. 
- Same thing with api_random_users.py during the refactoring code
- Overall I believe I should have keep transformations, saving in one file. Other files should just pull data from sources

2024-07-24 07:52 UTC, kraszewskigrzeg requested changes
Additional questions:
- should the api users be refactored too?
- did you merged main into current branch to assert all changes are there? (this is a little more advence and might not be applicable)

2024-07-24 07:52 UTC, kraszewskigrzeg commented on books/data_transformation.py
> +    args = parser.parse_args()
This is fine!

2024-07-24 07:52 UTC, kraszewskigrzeg commented on books/data_transformation.py
> +    # python books/data_transformation.py -t './_data/books/transformed' -s './_data/books/raw'
This is fine but..... If I were writing this script I would do it in a way that:
```python
transformation = DataTransformation()
transformation.transform_books(source_path=args.source_path, target_path=args.target_path)
```

and call only a single method to transform data :)

2024-07-24 07:52 UTC, kraszewskigrzeg commented on books/data_transformation.py
> +    def save_to_csv(self, data_type, target_path):
`data_type` is very missleading here :/

2024-07-24 07:52 UTC, kraszewskigrzeg commented on books/data_transformation.py
> +    def save_to_csv(self, data_type, target_path):
Generally this method could be moved outside of a class as it shoudl only save a dataframe nothing else.

2024-07-24 07:52 UTC, kraszewskigrzeg commented on books/data_transformation.py
> +        self.data_frames['api_users'] = df_users
this should not be here at all. Just save the results to the target file here :)

2024-07-24 07:52 UTC, kraszewskigrzeg commented on books/data_transformation.py
> +        self.data_frames['ratings'] = ratings_frame
this should not be here at all. Just save the results to the target file here :)

2024-07-24 07:52 UTC, kraszewskigrzeg commented on books/data_transformation.py
> +        self.data_frames['users'] = users_frame
this should not be here at all. Just save the results to the target file here :)

2024-07-24 07:52 UTC, kraszewskigrzeg commented on books/data_transformation.py
> +        self.data_frames['books'] = books_frame
this should not be here at all. Just save the results to the target file here :)

2024-07-24 13:57 UTC, kraszewskigrzeg commented on books/data_transformation.py
> +    # python books/data_transformation.py -t './_data/books/transformed' -s './_data/books/raw'
Yes exactly!

2024-07-24 13:58 UTC, kraszewskigrzeg commented on books/data_transformation.py
> +        books_frame = pd.read_csv(os.path.join(source_path, 'books.csv'), delimiter=';',
This to be discussed live!

2024-07-24 14:00 UTC, kraszewskigrzeg commented
I have resolved conflicts be sure to pull repo at your end before next changes :)

2024-08-28 13:39 UTC, kraszewskigrzeg approved these changes

2024-08-28 16:11 UTC, merged